### ISSUE TITLE
Feature request: copy to clipboard instead of journal page

### ISSUE THREAD

**Issue by stdword** [MateuszMyalski/logseq-plugin-shallow-copy#1]
To control the insertion place

**Comment by MateuszMyalski** [comment]
Yes, great idea to extend the functionality! As I am kind of fresh in logseq API environment, can you provide some examples how is it done in other places?

**Comment by stdword** [comment]
Check [these](https://github.com/stdword/logseq13-full-house-plugin/blob/main/src/app.tsx#L286-L287) code lines in my plugin.
And note: you need to set `effect: true` in marketplace's package.json

**Comment by MateuszMyalski** [comment]
Thank you for the response @stdword. I have refactored the code a bit and added the possibility to customize how the blocks are copied. Would you like to review the changes?

**Comment by stdword** [comment]
Just checked it — looks very nice and with cool setting to customize  ❤️

**Comment by MateuszMyalski** [comment]
Just noticed after releasing. Despite having "effect": true in the marketplace's .json it seems like the clipboard API get's blocked. ` DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.`
Did I forget to tell logseq something to enable this API @stdword?

**Comment by stdword** [comment]
`effect: true` should be [here](https://github.com/logseq/marketplace/blob/master/packages/logseq-shallow-copy/manifest.json) and approved by Logseq team

**Comment by MateuszMyalski** [comment]
Thanks! Just noticed I did not pushed it initially when introducing the plugin. Here is the pull request https://github.com/logseq/marketplace/pull/493
